pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git(
                    url: 'https://github.com/rachelanchan/DevOps.git',
                    credentialsId: 'github-pat',
                    branch: 'main'
                )
            }
        }
        stage('Build') {
            steps {
                echo 'Compiling Java program...'
                bat 'javac Lab2/HelloWorld.java'
            }
        }
        stage('Run') {
            steps {
                echo 'Running Java program...'
                bat 'java -cp Lab2/ HelloWorld' 
            }
        }
    }
}